
import bean.taikhoanbean;
import bo.taikhoanbo;
import dao.taikhoanchuyendao;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author phucp
 */
public class AtmChuyenTien extends javax.swing.JFrame {

    /**
     * Creates new form AtmChuyenTien
     */
    private taikhoanbean tk;
    public AtmChuyenTien(taikhoanbean tk) {
        this.tk = tk;
        initComponents();
    }

    private AtmChuyenTien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtTkChuyen = new javax.swing.JTextField();
        edtTienChuyen = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnChuyen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        edtTkChuyen.setText("xyz");
        edtTkChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTkChuyenActionPerformed(evt);
            }
        });

        edtTienChuyen.setText("50000");

        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnChuyen.setBackground(new java.awt.Color(204, 102, 255));
        btnChuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyen.setText("Chuyển");
        btnChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập tài khoản muốn chuyển");

        jLabel2.setText("Nhập số tiền muốn chuyển");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                            .addComponent(btnChuyen))
                        .addComponent(edtTkChuyen)
                        .addComponent(edtTienChuyen)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(edtTkChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTienChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnChuyen))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtTkChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTkChuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTkChuyenActionPerformed

    private void btnChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenActionPerformed
        try {
            long tienchuyen = Long.parseLong(edtTienChuyen.getText());
        
        if (tienchuyen % 50000!=0){
            JOptionPane.showMessageDialog(rootPane,  "Số tiền phải là bội số của 50.000 vnđ");
        }
        else if (tienchuyen > 5000000){
            JOptionPane.showMessageDialog(rootPane,  "Chỉ được chuyển tối đa 5 củ thôi");
        }
        else if (tienchuyen > tk.getSoTien()){
            JOptionPane.showMessageDialog(rootPane,  "Tiền trong tài khoản không đủ thì chuyển cái gì?");
        }
        else if (tienchuyen <0){
            JOptionPane.showMessageDialog(rootPane,  "Số âm thì làm sao mà chuyển");
        }
        else{
            taikhoanchuyendao dao = new taikhoanchuyendao();
            
            taikhoanbean tkhoannhan = dao.kttkhoan(edtTkChuyen.getText());
            
            if(tkhoannhan==null){
                
                JOptionPane.showMessageDialog(rootPane,  "Tài khoản cần chuyển tiền không đúng");
            }
            else{
                JOptionPane.showMessageDialog(rootPane,  "Chuyển tiền thành công");
                
                tk = AtmDangNhap.tt.chuyentien(tk, tkhoannhan, tienchuyen);
                
            }
            
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChuyenActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
        AtmClient client = new AtmClient(tk);
        client.setVisible(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtmChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtmChuyenTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyen;
    private javax.swing.JButton btnHuy;
    private javax.swing.JTextField edtTienChuyen;
    private javax.swing.JTextField edtTkChuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
